# Begin learning 
## Nikita Bulakhov edition

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 6, 4, 7, 9])

In [3]:
np.array([range(i,i+10) for i in a])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

### Генерация массивов

In [4]:
np.zeros((10, 10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
np.ones((2,10), dtype = float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
np.full((3,2), 3.1642)

array([[3.1642, 3.1642],
       [3.1642, 3.1642],
       [3.1642, 3.1642]])

In [7]:
np.arange(0, 10, 3, dtype = float)

array([0., 3., 6., 9.])

In [8]:
# Равномерное расспределение по области 
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.random.random((5,2))

array([[0.29095421, 0.89580042],
       [0.52797277, 0.25864508],
       [0.14125449, 0.60982107],
       [0.14013042, 0.96243392],
       [0.64515855, 0.05928972]])

In [10]:
np.random.randint(0,10, (3,3))

array([[0, 9, 0],
       [0, 7, 2],
       [6, 0, 8]])

In [11]:
np.eye(10, dtype = int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [12]:
np.empty((3,3))

array([[6.01346953e-154, 8.88780783e+252, 1.33168516e+179],
       [1.86927595e-152, 1.67432314e+243, 1.06185557e-153],
       [6.76989891e+223, 1.71010322e+214, 4.63362100e+228]])

In [13]:
x1 = np.arange(10)

In [14]:
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x1[9::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
x2 = np.random.randint(1,60,(6,6))
x2

array([[11, 57, 44,  3, 31, 26],
       [16,  6, 40, 43, 18, 54],
       [20, 53, 53,  5, 55, 46],
       [ 8, 12, 48, 36, 15, 10],
       [ 1, 52,  2, 52, 36, 12],
       [30, 53, 40, 59, 26,  1]])

In [17]:
x2[1::2, :2]

array([[16,  6],
       [ 8, 12],
       [30, 53]])

In [18]:
x2[::-1, ::-1]

array([[ 1, 26, 59, 40, 53, 30],
       [12, 36, 52,  2, 52,  1],
       [10, 15, 36, 48, 12,  8],
       [46, 55,  5, 53, 53, 20],
       [54, 18, 43, 40,  6, 16],
       [26, 31,  3, 44, 57, 11]])

In [19]:
x2[::-1,]

array([[30, 53, 40, 59, 26,  1],
       [ 1, 52,  2, 52, 36, 12],
       [ 8, 12, 48, 36, 15, 10],
       [20, 53, 53,  5, 55, 46],
       [16,  6, 40, 43, 18, 54],
       [11, 57, 44,  3, 31, 26]])

In [20]:
x2[0,:]

array([11, 57, 44,  3, 31, 26])

In [21]:
x2[0]

array([11, 57, 44,  3, 31, 26])

In [22]:
x2

array([[11, 57, 44,  3, 31, 26],
       [16,  6, 40, 43, 18, 54],
       [20, 53, 53,  5, 55, 46],
       [ 8, 12, 48, 36, 15, 10],
       [ 1, 52,  2, 52, 36, 12],
       [30, 53, 40, 59, 26,  1]])

### Without copy (sub_arr changes will be in x2)

In [23]:
sub_arr = x2[1:4, 1:4]
sub_arr[0][0] = 95

In [24]:
sub_arr

array([[95, 40, 43],
       [53, 53,  5],
       [12, 48, 36]])

In [25]:
x2

array([[11, 57, 44,  3, 31, 26],
       [16, 95, 40, 43, 18, 54],
       [20, 53, 53,  5, 55, 46],
       [ 8, 12, 48, 36, 15, 10],
       [ 1, 52,  2, 52, 36, 12],
       [30, 53, 40, 59, 26,  1]])

### With copy

In [26]:
x3 = np.zeros((5,5), dtype=np.int64)
x3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [27]:
sub_arr = x3[1:4, 1:4].copy()
sub_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [28]:
sub_arr[0][0] = 95
sub_arr

array([[95,  0,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]], dtype=int64)

In [29]:
x3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [30]:
numbers = np.arange(1, 61)

In [31]:
new_numbers = numbers.reshape((6,10))

In [32]:
new_numbers[:, 9:]

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [33]:
numbers[:2,np.newaxis]

array([[1],
       [2]])

In [34]:
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)

In [35]:
arr1

array([1, 2, 3, 4])

In [36]:
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
grid = np.array([[1, 2, 3], [6, 4, 8], [6, 4, 8]])
xyz = np.array([1, 2, 3])

In [38]:
np.vstack([grid, grid])

array([[1, 2, 3],
       [6, 4, 8],
       [6, 4, 8],
       [1, 2, 3],
       [6, 4, 8],
       [6, 4, 8]])

In [39]:
np.hstack([grid, xyz[:, np.newaxis]])

array([[1, 2, 3, 1],
       [6, 4, 8, 2],
       [6, 4, 8, 3]])

In [87]:
grid = np.reshape(grid, [1, 9])
grid[:np.newaxis]

array([[1, 2, 3, 6, 4, 8, 6, 4, 8]])

In [88]:
np.split(grid[0], [3, 6])

[array([1, 2, 3]), array([6, 4, 8]), array([6, 4, 8])]

In [89]:
grid2 = np.arange(1,37).reshape([6,6])

In [91]:
grid2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [106]:
np.vsplit(grid2, np.array([2, 4]))


[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]